2025-09-12T22:14:02 {"cpu": 0.12646484375, "cpu_total": 12, "cpu_usage": 0.010538736979166666, "memory": 2221.0, "memory_total": 19929.0, "memory_usage": 0.1114456319935772, "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 10 in schedule 6 is alive.", "timestamp": 1757715242.744987, "uuid": "650c633e0f0d43e4821b41284c7fad1b"}
2025-09-12T22:14:02 {"cpu": 0.12646484375, "cpu_total": 12, "cpu_usage": 0.010538736979166666, "memory": 2248.0, "memory_total": 19929.0, "memory_usage": 0.11280044156756486, "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 10 in schedule 6 is alive.", "timestamp": 1757715242.976274, "uuid": "96adebd62b924d07bed31228b5fa8b60"}
2025-09-12T22:14:03 {"block_run_id": 28, "block_uuid": "ingest_qb_items", "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 10, BlockRun 28: pipeline qb_items_backfill block ingest_qb_items", "timestamp": 1757715243.035049, "uuid": "a61d829097f842d88465d9faeaa53260"}
2025-09-12T22:14:12 {"cpu": 0.12451171875, "cpu_total": 12, "cpu_usage": 0.0103759765625, "memory": 2264.0, "memory_total": 19929.0, "memory_usage": 0.11360329168548347, "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 10 in schedule 6 is alive.", "timestamp": 1757715252.41893, "uuid": "04eb985b87914e57a4e999cc2ff75a5b"}
2025-09-12T22:14:14 {"block_run_id": 28, "block_uuid": "ingest_qb_items", "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "BlockRun 28 (block_uuid: ingest_qb_items) completes.", "timestamp": 1757715254.309703, "uuid": "e29687c880f84f11b45071c63eb96dfb"}
2025-09-12T22:14:22 {"cpu": 0.12841796875, "cpu_total": 12, "cpu_usage": 0.010701497395833334, "memory": 2224.0, "memory_total": 19929.0, "memory_usage": 0.11159616639068694, "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 10 in schedule 6 is alive.", "timestamp": 1757715262.774094, "uuid": "852bd355aafc40b8ae707d6c0c881b47"}
2025-09-12T22:14:23 {"block_run_id": 29, "block_uuid": "transform_qb_items", "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 10, BlockRun 29: pipeline qb_items_backfill block transform_qb_items", "timestamp": 1757715263.024328, "uuid": "39e0fc9b42cf462a81f2dcfdbde74f70"}
2025-09-12T22:14:24 {"block_run_id": 29, "block_uuid": "transform_qb_items", "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "EXCEPTION", "message": "BlockRun 29 (block_uuid: transform_qb_items) failed.", "timestamp": 1757715264.05375, "uuid": "149ff15590054287b4c8058d690781bd", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3385, in run_tests\n    raise Exception(f'Failed to pass tests for block {self.uuid}')\nException: Failed to pass tests for block transform_qb_items\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "Failed to pass tests for block transform_qb_items"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1185, in _execute
    self.block.run_tests(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 3385, in run_tests
    raise Exception(f'Failed to pass tests for block {self.uuid}')
Exception: Failed to pass tests for block transform_qb_items
2025-09-12T22:14:33 {"cpu": 0.13232421875, "cpu_total": 12, "cpu_usage": 0.011027018229166666, "memory": 2221.0, "memory_total": 19929.0, "memory_usage": 0.1114456319935772, "pipeline_run_id": 10, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 10 in schedule 6 is alive.", "timestamp": 1757715273.30832, "uuid": "dee9fef3924945aaba06d8be099a6964"}
2025-09-12T22:14:52 {"cpu": 0.13427734375, "cpu_total": 12, "cpu_usage": 0.011189778645833334, "memory": 2224.0, "memory_total": 19929.0, "memory_usage": 0.11159616639068694, "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 11 in schedule 6 is alive.", "timestamp": 1757715292.968919, "uuid": "c744e5fc0353463d853d48bf422b1fa0"}
2025-09-12T22:14:53 {"cpu": 0.13427734375, "cpu_total": 12, "cpu_usage": 0.011189778645833334, "memory": 2254.0, "memory_total": 19929.0, "memory_usage": 0.11310151036178434, "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 11 in schedule 6 is alive.", "timestamp": 1757715293.215974, "uuid": "213f34af454f4e1b9ca19997ab9baa95"}
2025-09-12T22:14:53 {"block_run_id": 31, "block_uuid": "ingest_qb_items", "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 11, BlockRun 31: pipeline qb_items_backfill block ingest_qb_items", "timestamp": 1757715293.274801, "uuid": "dddaa74528d9404fb752ec9f66cab6fd"}
2025-09-12T22:15:02 {"cpu": 0.13232421875, "cpu_total": 12, "cpu_usage": 0.011027018229166666, "memory": 2267.0, "memory_total": 19929.0, "memory_usage": 0.11375382608259321, "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 11 in schedule 6 is alive.", "timestamp": 1757715302.629282, "uuid": "32cba15a4fc347ada6f9e20fa8a4cd39"}
2025-09-12T22:15:04 {"block_run_id": 31, "block_uuid": "ingest_qb_items", "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "BlockRun 31 (block_uuid: ingest_qb_items) completes.", "timestamp": 1757715304.515769, "uuid": "41e135ac901247aaa22dfdf1706b2bd7"}
2025-09-12T22:15:12 {"cpu": 0.13037109375, "cpu_total": 12, "cpu_usage": 0.0108642578125, "memory": 2220.0, "memory_total": 19929.0, "memory_usage": 0.11139545386120729, "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 11 in schedule 6 is alive.", "timestamp": 1757715312.943182, "uuid": "4e1ce25775044ba084354ef3af8eb781"}
2025-09-12T22:15:13 {"block_run_id": 32, "block_uuid": "transform_qb_items", "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 11, BlockRun 32: pipeline qb_items_backfill block transform_qb_items", "timestamp": 1757715313.304861, "uuid": "88d86327115b4be18bced9b5ac5de573"}
2025-09-12T22:15:14 {"block_run_id": 32, "block_uuid": "transform_qb_items", "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "EXCEPTION", "message": "BlockRun 32 (block_uuid: transform_qb_items) failed.", "timestamp": 1757715314.837289, "uuid": "879e60203daa4e358a4acbf443af3042", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3385, in run_tests\n    raise Exception(f'Failed to pass tests for block {self.uuid}')\nException: Failed to pass tests for block transform_qb_items\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "Failed to pass tests for block transform_qb_items"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1185, in _execute
    self.block.run_tests(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 3385, in run_tests
    raise Exception(f'Failed to pass tests for block {self.uuid}')
Exception: Failed to pass tests for block transform_qb_items
2025-09-12T22:15:22 {"cpu": 0.12841796875, "cpu_total": 12, "cpu_usage": 0.010701497395833334, "memory": 2218.0, "memory_total": 19929.0, "memory_usage": 0.11129509759646745, "pipeline_run_id": 11, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 11 in schedule 6 is alive.", "timestamp": 1757715322.451431, "uuid": "e4df426963704f25a753c0bdcdeef104"}
2025-09-12T22:16:52 {"cpu": 0.11669921875, "cpu_total": 12, "cpu_usage": 0.009724934895833334, "memory": 2226.0, "memory_total": 19929.0, "memory_usage": 0.11169652265542676, "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 12 in schedule 6 is alive.", "timestamp": 1757715412.787016, "uuid": "472cd31431b847e5aaf44a817a5e97ab"}
2025-09-12T22:16:53 {"cpu": 0.11669921875, "cpu_total": 12, "cpu_usage": 0.009724934895833334, "memory": 2260.0, "memory_total": 19929.0, "memory_usage": 0.11340257915600381, "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 12 in schedule 6 is alive.", "timestamp": 1757715413.049388, "uuid": "0ceebb0cdc484e5ca9b60a677d7d04bc"}
2025-09-12T22:16:53 {"block_run_id": 34, "block_uuid": "ingest_qb_items", "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 12, BlockRun 34: pipeline qb_items_backfill block ingest_qb_items", "timestamp": 1757715413.111098, "uuid": "27423f7c9a754bcf8ca70d04795f4c23"}
2025-09-12T22:17:02 {"cpu": 0.11474609375, "cpu_total": 12, "cpu_usage": 0.009562174479166666, "memory": 2270.0, "memory_total": 19929.0, "memory_usage": 0.11390436047970294, "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 12 in schedule 6 is alive.", "timestamp": 1757715422.472481, "uuid": "5f2fbbaaeb5549309be12ef3bd822212"}
2025-09-12T22:17:04 {"block_run_id": 34, "block_uuid": "ingest_qb_items", "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "BlockRun 34 (block_uuid: ingest_qb_items) completes.", "timestamp": 1757715424.854447, "uuid": "43f905c491d44c249a18ea3871951970"}
2025-09-12T22:17:12 {"cpu": 0.11279296875, "cpu_total": 12, "cpu_usage": 0.0093994140625, "memory": 2222.0, "memory_total": 19929.0, "memory_usage": 0.11149581012594711, "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 12 in schedule 6 is alive.", "timestamp": 1757715432.883691, "uuid": "41250767e5ed45d2812c9a66222ce0ab"}
2025-09-12T22:17:13 {"block_run_id": 35, "block_uuid": "transform_qb_items", "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 12, BlockRun 35: pipeline qb_items_backfill block transform_qb_items", "timestamp": 1757715433.240993, "uuid": "a093d4f9195b46adab403a48486dd05c"}
2025-09-12T22:17:14 {"block_run_id": 35, "block_uuid": "transform_qb_items", "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "EXCEPTION", "message": "BlockRun 35 (block_uuid: transform_qb_items) failed.", "timestamp": 1757715434.460581, "uuid": "3bb344a3faf240679f3969dfc9b35341", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3385, in run_tests\n    raise Exception(f'Failed to pass tests for block {self.uuid}')\nException: Failed to pass tests for block transform_qb_items\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "Failed to pass tests for block transform_qb_items"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1185, in _execute
    self.block.run_tests(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 3385, in run_tests
    raise Exception(f'Failed to pass tests for block {self.uuid}')
Exception: Failed to pass tests for block transform_qb_items
2025-09-12T22:17:22 {"cpu": 0.11083984375, "cpu_total": 12, "cpu_usage": 0.009236653645833334, "memory": 2226.0, "memory_total": 19929.0, "memory_usage": 0.11169652265542676, "pipeline_run_id": 12, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 12 in schedule 6 is alive.", "timestamp": 1757715442.435543, "uuid": "916ee22e4d78430286ef99ee1483880c"}
2025-09-12T22:21:13 {"cpu": 0.091796875, "cpu_total": 12, "cpu_usage": 0.007649739583333333, "memory": 2231.0, "memory_total": 19929.0, "memory_usage": 0.11194741331727633, "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 14 in schedule 6 is alive.", "timestamp": 1757715673.408825, "uuid": "b12bcb66aea941328f91c72bca43bd55"}
2025-09-12T22:21:13 {"block_run_id": 40, "block_uuid": "ingest_qb_items", "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 14, BlockRun 40: pipeline qb_items_backfill block ingest_qb_items", "timestamp": 1757715673.754504, "uuid": "4915907d650f4de285cfa9b530d696cf"}
2025-09-12T22:21:13 {"cpu": 0.091796875, "cpu_total": 12, "cpu_usage": 0.007649739583333333, "memory": 2272.0, "memory_total": 19929.0, "memory_usage": 0.11400471674444278, "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 14 in schedule 6 is alive.", "timestamp": 1757715673.927882, "uuid": "fff8a9d38d844c37ae47a8f93c8b8529"}
2025-09-12T22:21:23 {"cpu": 0.09033203125, "cpu_total": 12, "cpu_usage": 0.007527669270833333, "memory": 2285.0, "memory_total": 19929.0, "memory_usage": 0.11465703246525165, "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 14 in schedule 6 is alive.", "timestamp": 1757715683.707754, "uuid": "786194e5c1154dff87760a32c9a6d68c"}
2025-09-12T22:21:24 {"block_run_id": 40, "block_uuid": "ingest_qb_items", "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "BlockRun 40 (block_uuid: ingest_qb_items) completes.", "timestamp": 1757715684.946969, "uuid": "a603a3b6542a4fa08b0a7f627ff86539"}
2025-09-12T22:21:35 {"cpu": 0.1103515625, "cpu_total": 12, "cpu_usage": 0.009195963541666666, "memory": 2233.0, "memory_total": 19929.0, "memory_usage": 0.11204776958201616, "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 14 in schedule 6 is alive.", "timestamp": 1757715695.690731, "uuid": "c26df7caaaa44180ba38d68533587c7d"}
2025-09-12T22:21:36 {"block_run_id": 41, "block_uuid": "transform_qb_items", "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 14, BlockRun 41: pipeline qb_items_backfill block transform_qb_items", "timestamp": 1757715696.041471, "uuid": "ed400d49ce724c24b9cc981e60f4755d"}
2025-09-12T22:21:37 {"block_run_id": 41, "block_uuid": "transform_qb_items", "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "EXCEPTION", "message": "BlockRun 41 (block_uuid: transform_qb_items) failed.", "timestamp": 1757715697.228679, "uuid": "cf6e1daa655f4dfea574008ab88072b1", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3385, in run_tests\n    raise Exception(f'Failed to pass tests for block {self.uuid}')\nException: Failed to pass tests for block transform_qb_items\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "Failed to pass tests for block transform_qb_items"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1185, in _execute
    self.block.run_tests(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 3385, in run_tests
    raise Exception(f'Failed to pass tests for block {self.uuid}')
Exception: Failed to pass tests for block transform_qb_items
2025-09-12T22:21:44 {"cpu": 0.109375, "cpu_total": 12, "cpu_usage": 0.009114583333333334, "memory": 2233.0, "memory_total": 19929.0, "memory_usage": 0.11204776958201616, "pipeline_run_id": 14, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 14 in schedule 6 is alive.", "timestamp": 1757715704.309963, "uuid": "5c31758166b4493c8455cd9b18a94e4f"}
