2025-09-12T22:13:12 {"cpu": 0.12451171875, "cpu_total": 12, "cpu_usage": 0.0103759765625, "memory": 2214.0, "memory_total": 19929.0, "memory_usage": 0.11109438506698781, "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 8 in schedule 6 is alive.", "timestamp": 1757715192.845705, "uuid": "313fd2536d1c4713b09777de3a86bcee"}
2025-09-12T22:13:13 {"cpu": 0.12451171875, "cpu_total": 12, "cpu_usage": 0.0103759765625, "memory": 2256.0, "memory_total": 19929.0, "memory_usage": 0.11320186662652416, "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 8 in schedule 6 is alive.", "timestamp": 1757715193.096188, "uuid": "154ba828f6bf4239be9f06b8e845c658"}
2025-09-12T22:13:13 {"block_run_id": 22, "block_uuid": "ingest_qb_items", "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 8, BlockRun 22: pipeline qb_items_backfill block ingest_qb_items", "timestamp": 1757715193.148803, "uuid": "564ddbb2aba8437d9490596b831a52bd"}
2025-09-12T22:13:22 {"cpu": 0.12841796875, "cpu_total": 12, "cpu_usage": 0.010701497395833334, "memory": 2279.0, "memory_total": 19929.0, "memory_usage": 0.11435596367103217, "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 8 in schedule 6 is alive.", "timestamp": 1757715202.997291, "uuid": "4b416bebbe454bfab51895fa8098e1e6"}
2025-09-12T22:13:25 {"block_run_id": 22, "block_uuid": "ingest_qb_items", "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "BlockRun 22 (block_uuid: ingest_qb_items) completes.", "timestamp": 1757715205.001278, "uuid": "45e8afca7944406c9a1f6404f94fba2b"}
2025-09-12T22:13:32 {"cpu": 0.12646484375, "cpu_total": 12, "cpu_usage": 0.010538736979166666, "memory": 2218.0, "memory_total": 19929.0, "memory_usage": 0.11129509759646745, "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 8 in schedule 6 is alive.", "timestamp": 1757715212.539834, "uuid": "9078d5090492421b9aa7088167305900"}
2025-09-12T22:13:32 {"block_run_id": 23, "block_uuid": "transform_qb_items", "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Execute PipelineRun 8, BlockRun 23: pipeline qb_items_backfill block transform_qb_items", "timestamp": 1757715212.848221, "uuid": "2039af37a1db44c39446b1d74d56cd07"}
2025-09-12T22:13:34 {"block_run_id": 23, "block_uuid": "transform_qb_items", "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "EXCEPTION", "message": "BlockRun 23 (block_uuid: transform_qb_items) failed.", "timestamp": 1757715214.13227, "uuid": "9a0928f97d5148d1b3fa8f1f384c89be", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1185, in _execute\n    self.block.run_tests(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 3385, in run_tests\n    raise Exception(f'Failed to pass tests for block {self.uuid}')\nException: Failed to pass tests for block transform_qb_items\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "Failed to pass tests for block transform_qb_items"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1185, in _execute
    self.block.run_tests(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 3385, in run_tests
    raise Exception(f'Failed to pass tests for block {self.uuid}')
Exception: Failed to pass tests for block transform_qb_items
2025-09-12T22:13:42 {"cpu": 0.12451171875, "cpu_total": 12, "cpu_usage": 0.0103759765625, "memory": 2219.0, "memory_total": 19929.0, "memory_usage": 0.11134527572883737, "pipeline_run_id": 8, "pipeline_schedule_id": 6, "pipeline_uuid": "qb_items_backfill", "hostname": "ef0b07a8432d", "level": "INFO", "message": "Pipeline qb_items_backfill for run 8 in schedule 6 is alive.", "timestamp": 1757715222.452005, "uuid": "d569479809db4bfc906a5ef61391a215"}
